# Generated by Django 5.0.4 on 2024-04-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activiteit",
            fields=[
                ("activiteit_id", models.AutoField(primary_key=True, serialize=False)),
                ("stap", models.IntegerField(null=True)),
                ("taak", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Gebruiker",
            fields=[
                ("gebruikers_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_docent_student", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                (
                    "profielfoto",
                    models.ImageField(null=True, upload_to="profielfotos/"),
                ),
                ("bio", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Domein",
            fields=[
                ("domein_id", models.AutoField(primary_key=True, serialize=False)),
                ("domeinnaam", models.CharField(max_length=100)),
                (
                    "bovenliggend_domein",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.domein",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cursusjaar",
            fields=[
                ("cursusjaar_id", models.AutoField(primary_key=True, serialize=False)),
                ("naam", models.CharField(max_length=100)),
                ("cursusjaar", models.CharField(max_length=100)),
                (
                    "domein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="glitch.domein"
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cursus",
            fields=[
                ("vak_cursus_id", models.AutoField(primary_key=True, serialize=False)),
                ("vaknaam", models.CharField(max_length=100)),
                (
                    "domein",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.domein",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoreAssignment",
            fields=[
                ("opdracht_id", models.AutoField(primary_key=True, serialize=False)),
                ("opdrachtnaam", models.CharField(max_length=100)),
                ("deadline", models.DateField(null=True)),
                ("score", models.IntegerField(null=True)),
                (
                    "bijlage",
                    models.FileField(null=True, upload_to="opdracht_bijlagen/"),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("challenge_id", models.AutoField(primary_key=True, serialize=False)),
                ("point_concept_chalenge", models.IntegerField()),
                ("verzamelde_punten", models.IntegerField(null=True)),
                (
                    "activiteit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.activiteit",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activiteit",
            name="gebruiker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="glitch.gebruiker",
            ),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("module_id", models.AutoField(primary_key=True, serialize=False)),
                ("modulenaam", models.CharField(max_length=100)),
                ("beschrijving", models.TextField()),
                (
                    "activiteit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="glitch.activiteit",
                    ),
                ),
                (
                    "chalenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.challenge",
                    ),
                ),
                (
                    "cursus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.cursus",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
                (
                    "opdracht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.coreassignment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activiteit",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activiteiten",
                to="glitch.module",
            ),
        ),
        migrations.CreateModel(
            name="Notificatie",
            fields=[
                ("notificatie_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(null=True)),
                ("beschrijving", models.TextField(null=True)),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Onderwijsperiode",
            fields=[
                (
                    "onderwijsperiode_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("periode", models.CharField(max_length=100)),
                (
                    "cursusjaar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.cursusjaar",
                    ),
                ),
                (
                    "domein",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.domein",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cursus",
            name="onderwijsperiode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="glitch.onderwijsperiode",
            ),
        ),
        migrations.CreateModel(
            name="Voortgang",
            fields=[
                ("voortgang_id", models.AutoField(primary_key=True, serialize=False)),
                ("totale_score", models.IntegerField(null=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glitch.cursus",
                    ),
                ),
                (
                    "gebruiker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voortgang_gebruikers",
                        to="glitch.gebruiker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="module",
            name="voortgang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="glitch.voortgang"
            ),
        ),
        migrations.AddField(
            model_name="gebruiker",
            name="voortgang",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gebruikers_voortgang",
                to="glitch.voortgang",
            ),
        ),
    ]
