# Generated by Django 5.0.1 on 2024-05-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursusjaar',
            name='naam',
        ),
    ]
