# Generated by Django 5.0.1 on 2024-05-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruiker',
            name='achternaam',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='voornaam',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
