# Generated by Django 5.0.4 on 2024-06-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreassignment',
            old_name='context_challenge',
            new_name='concept_challenge',
        ),
        migrations.AddField(
            model_name='activiteit',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glitch.cursus'),
        ),
    ]
