# Generated by Django 5.0.4 on 2024-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glitch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gebruiker",
            name="profielfoto",
            field=models.ImageField(null=True, upload_to="static/img/"),
        ),
    ]
