# Generated by Django 5.0.4 on 2024-06-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0002_rename_context_challenge_coreassignment_concept_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteit',
            name='status',
            field=models.CharField(choices=[('INGEDIEND', 'Ingediend'), ('AFGEKEURD', 'Afgekeurd'), ('GOEDGEKEURD', 'Goedgekeurd')], default='INGEDIEND', max_length=12),
        ),
    ]
