# Generated by Django 5.0.1 on 2024-05-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0002_remove_cursusjaar_naam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='domein',
        ),
        migrations.AddField(
            model_name='cursus',
            name='cursusjaar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glitch.cursusjaar'),
        ),
        migrations.AddField(
            model_name='cursus',
            name='cursusnaam',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
