# Generated by Django 5.0.1 on 2024-05-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0002_remove_cursusjaar_naam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='onderwijsperiode',
        ),
        migrations.DeleteModel(
            name='Onderwijsperiode',
        ),
    ]
