# Generated by Django 5.0.4 on 2024-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glitch", "0003_activiteit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activiteit",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
