# Generated by Django 5.0.1 on 2024-05-21 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0003_remove_cursus_domein_cursus_cursusjaar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='gebruiker',
        ),
        migrations.RemoveField(
            model_name='cursusjaar',
            name='gebruiker',
        ),
        migrations.RemoveField(
            model_name='domein',
            name='bovenliggend_domein',
        ),
        migrations.RemoveField(
            model_name='domein',
            name='gebruiker',
        ),
        migrations.AddField(
            model_name='cursus',
            name='gebruikers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursusjaar',
            name='gebruikers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domein',
            name='gebruikers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='cursusjaren',
            field=models.ManyToManyField(to='glitch.cursusjaar'),
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='cursussen',
            field=models.ManyToManyField(to='glitch.cursus'),
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='domeinen',
            field=models.ManyToManyField(to='glitch.domein'),
        ),
    ]
