# Generated by Django 5.0.1 on 2024-05-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0003_remove_cursus_onderwijsperiode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='point_concept_chalenge',
            new_name='point_concept_challenge',
        ),
    ]
