# Generated by Django 5.0.1 on 2024-05-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0004_rename_point_concept_chalenge_challenge_point_concept_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='gebruiker',
        ),
        migrations.CreateModel(
            name='Deelname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glitch.cursus')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='cursussen',
            field=models.ManyToManyField(through='glitch.Deelname', to='glitch.cursus'),
        ),
    ]
