# Generated by Django 5.0.1 on 2024-05-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0004_remove_cursus_gebruiker_remove_cursusjaar_gebruiker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='onderwijsperiode',
        ),
        migrations.DeleteModel(
            name='Onderwijsperiode',
        ),
    ]
