# Generated by Django 5.0.1 on 2024-05-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0005_remove_cursus_gebruiker_deelname_gebruiker_cursussen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursusjaar',
            name='gebruiker',
        ),
        migrations.RemoveField(
            model_name='domein',
            name='gebruiker',
        ),
        migrations.CreateModel(
            name='CursusjaarCursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glitch.cursus')),
                ('cursusjaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glitch.cursusjaar')),
            ],
        ),
        migrations.AddField(
            model_name='cursusjaar',
            name='cursussen',
            field=models.ManyToManyField(through='glitch.CursusjaarCursus', to='glitch.cursus'),
        ),
    ]
