# Generated by Django 5.0.4 on 2024-06-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0005_voortgang_status_voortgang_submission_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiteit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='voortgang',
            name='afgevinkt',
        ),
        migrations.RemoveField(
            model_name='voortgang',
            name='bijlage',
        ),
    ]
