# Generated by Django 5.0.4 on 2024-06-26 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0006_remove_activiteit_status_remove_voortgang_afgevinkt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiteit',
            name='afgevinkt',
        ),
        migrations.RemoveField(
            model_name='activiteit',
            name='gebruiker',
        ),
        migrations.RemoveField(
            model_name='activiteit',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='coreassignment',
            name='gebruikers',
        ),
        migrations.CreateModel(
            name='GebruikerActiviteit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4')], default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AFWACHTING', 'Afwachting'), ('GOEDGEKEURD', 'Goedgekeurd'), ('AFGEKEURD', 'Afgekeurd')], default='OPEN', max_length=11)),
                ('activiteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glitch.activiteit')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GebruikerCoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AFWACHTING', 'Afwachting'), ('GOEDGEKEURD', 'Goedgekeurd'), ('AFGEKEURD', 'Afgekeurd')], default='OPEN', max_length=11)),
                ('core_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glitch.coreassignment')),
                ('gebruiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
