# Generated by Django 5.0.1 on 2024-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0006_remove_cursusjaar_gebruiker_remove_domein_gebruiker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteit',
            name='afgevinkt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activiteit',
            name='niveau',
            field=models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4')], default=1),
        ),
        migrations.AddField(
            model_name='coreassignment',
            name='afgevinkt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coreassignment',
            name='context_challenge',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coreassignment',
            name='point_challenge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gebruiker',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
