# Generated by Django 5.0.1 on 2024-05-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0007_activiteit_afgevinkt_activiteit_niveau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreassignment',
            old_name='opdracht_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='activiteit',
            name='core_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activiteiten', to='glitch.coreassignment'),
        ),
    ]
