# Generated by Django 5.0.4 on 2024-06-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0007_remove_activiteit_afgevinkt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruikeractiviteit',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gebruikercoreassignment',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
