# Generated by Django 5.0.4 on 2024-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glitch", "0008_gebruikeractiviteit_submission_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activiteit",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
