# Generated by Django 5.0.1 on 2024-05-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0008_rename_opdracht_id_coreassignment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreassignment',
            old_name='id',
            new_name='opdracht_id',
        ),
    ]
