# Generated by Django 5.0.4 on 2024-06-28 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glitch', '0010_alter_gebruiker_profielfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificatie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
